import Head from "next/head";
import { useState } from "react";
import Calender from "react-calendar";

export default function Home() {
  const [date, setDate] = useState(new Date());
  const [event, setEvent] = useState([]);
  const [visible, setVisible] = useState(false);
  const [time, setTime] = useState(undefined);
  const [disp, setDisp] = useState("");

  const handleEvent = (e) => {
    e.preventDefault();
    setVisible(false);

    console.log(time, disp, date);

    if (!time || time.startTime > time.endTime || !disp) return;

    if (time.startTime > 24 || time.endTime > 24) return;

    console.log("ALl paased");
    setEvent([...event, { date, ...time, disp }]);
    setTime(undefined);
    setDisp("");
  };

  const handleVisible = (e) => {
    setVisible((visible) => !visible);
    console.log("got it");
  };

  console.log(visible);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Calender onChange={setDate} />
        <button onClick={handleVisible}>Click here to add Event</button>

        {event?.map(
          (e, index) =>
            e.date.toDateString() == date.toDateString() && (
              <div key={index}>
                <span style={{ padding: "1rem" }}>Description {e.disp} </span>
                <span style={{ padding: "1rem" }}>StartTime {e.startTime}</span>
                <span style={{ padding: "1rem" }}> EndTime {e.endTime}</span>
              </div>
            )
        )}
        {visible && (
          <div>
            <input
              value={time?.startTime || ""}
              type="number"
              onChange={(e) =>
                setTime({
                  ...time,
                  startTime: Number.parseInt(e.currentTarget.value),
                })
              }
            />{" "}
            <input
              type="number"
              value={time?.endTime || ""}
              onChange={(e) =>
                setTime({
                  ...time,
                  endTime: Number.parseInt(e.currentTarget.value),
                })
              }
            />
            <input
              value={disp}
              onChange={(e) => setDisp(e.currentTarget.value)}
            />
            <button onClick={handleEvent}>Add Event </button>
          </div>
        )}
      </main>
    </div>
  );
}
